version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 7306:3306
    volumes:
      - ./mariadb/data-backup:/var/lib/mysql
    container_name: 'ASP-TDD-DBASE'

  adminer:
    image: adminer
    restart: always
    ports:
      - 7080:8080
    container_name: 'ASP-TDD-ADMINER'
